name: update-companies-data
on:
  schedule:
    # Runs "at 18:45 (Nepal Time), every Sunday to Thrusday
    - cron: "10 21 * * 0-4"
  workflow_dispatch:
jobs:
  update-daily-data:
    name: update-daily-data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          node-version: "20"
      - name: Install packages
        run: npm install
      - name: Run updater
        run: node ./src/DailynewsScrapper.js && node ./src/dailyDataScrapper.js
      - name: Setup Git
        run: git config --local user.email "pawanawasthi481@gmail.com" && git config --local user.name "Pawan Awasthi"
      - name: Commit Files
        run: git add . && git commit -m "Update data"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
